# Generated by Django 3.1.7 on 2021-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydraws',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
