# Generated by Django 3.1.7 on 2021-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0003_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydraws',
            name='prize',
            field=models.ManyToManyField(to='luckydraw.Prizes'),
        ),
    ]
