# Generated by Django 3.1.7 on 2021-03-27 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0004_luckydraws_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipants',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameparticipants',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luckydraw.tickets'),
        ),
        migrations.AddField(
            model_name='gameparticipants',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='luckydraws',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luckydraw.tickets'),
        ),
        migrations.AddField(
            model_name='luckydraws',
            name='winning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
