# Generated by Django 3.1.7 on 2021-03-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0006_gameparticipants_is_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDrawWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lucky_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luckydraw.luckydraws')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luckydraw.prizes')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luckydraw.tickets')),
            ],
        ),
    ]
