# Generated by Django 3.1.7 on 2021-03-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0007_luckydrawwinners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckydraws',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='luckydraws',
            name='winning_date',
        ),
    ]
