# Generated by Django 3.1.7 on 2021-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0008_auto_20210327_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizes',
            name='is_winner_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
